--- 
version: "2"
networks:
  default:
    driver: bridge
    ipam:
      config:
      - subnet: 172.16.239.0/24
  traefik_proxy: 
    external: 
      name: traefik_proxy
services: 
  taisun:
    image: linuxserver/taisun
    container_name: taisun
    ports:
      - "3000:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks:
      - traefik_proxy
    environment:
      - TZ=America/Chicago
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - FILE__PASSWORD=/mnt/storage/appdata/taisun/password
    labels:
      - traefik.enable=true
      - traefik.backend=taisun
      - "traefik.frontend.rule=Host:taisun.${DOMAINNAME}"
      - traefik.port=3000
      - traefik.docker.network=traefik_proxy
      - traefik.frontend.headers.SSLRedirect=true
      - traefik.frontend.headers.STSSeconds=315360000
      - traefik.frontend.headers.browserXSSFilter=true
      - traefik.frontend.headers.contentTypeNosniff=true
      - traefik.frontend.headers.forceSTSHeader=true
      - traefik.frontend.headers.SSLHost=frost.haus
      - traefik.frontend.headers.STSIncludeSubdomains=true
      - traefik.frontend.headers.STSPreload=true
      - traefik.frontend.headers.frameDeny=false
  lazylibrarian:
    image: linuxserver/lazylibrarian:latest
    container_name: lazylibrarian
    environment:
      - TZ=America/Chicago
      - "PUID=${PUID}"
      - "PGID=${PGID}"
    volumes:
      - /mnt/storage/appdata/lazy:/config
      - /mnt/storage/media/downloads:/downloads
      - /mnt/storage/media/books:/books
    restart: unless-stopped
    labels: 
      - traefik.enable=true
      - traefik.backend=lazylibrarian
      - "traefik.frontend.rule=Host:lazylibrarian.${DOMAINNAME}"
      - traefik.port=5299
      - traefik.docker.network=traefik_proxy
      - traefik.frontend.headers.SSLRedirect=true
      - traefik.frontend.headers.STSSeconds=315360000
      - traefik.frontend.headers.browserXSSFilter=true
      - traefik.frontend.headers.contentTypeNosniff=true
      - traefik.frontend.headers.forceSTSHeader=true
      - traefik.frontend.headers.SSLHost=frost.haus
      - traefik.frontend.headers.STSIncludeSubdomains=true
      - traefik.frontend.headers.STSPreload=true
      - traefik.frontend.headers.frameDeny=false
    networks: 
      - traefik_proxy
#  mylar: 
#    container_name: mylar
#    environment: 
#      - TZ=America/Chicago
#      - "PUID=${PUID}"
#      - "PGID=${PGID}"
#    image: linuxserver/mylar:latest
#    labels: 
#      - traefik.enable=true
#      - traefik.backend=mylar
#      - "traefik.frontend.rule=Host:mylar.${DOMAINNAME}"
#      - traefik.port=8090
#      - traefik.docker.network=traefik_proxy
#      - traefik.frontend.headers.SSLRedirect=true
#      - traefik.frontend.headers.STSSeconds=315360000
#      - traefik.frontend.headers.browserXSSFilter=true
#      - traefik.frontend.headers.contentTypeNosniff=true
#      - traefik.frontend.headers.forceSTSHeader=true
#      - traefik.frontend.headers.SSLHost=frost.haus
#      - traefik.frontend.headers.STSIncludeSubdomains=true
#      - traefik.frontend.headers.STSPreload=true
#      - traefik.frontend.headers.frameDeny=false
#    networks: 
#      - traefik_proxy
#    volumes: 
#      - "/mnt/storage/appdata/mylar:/config"
#      - "/mnt/storage/media/comics-import:/comics-import"
#      - "/mnt/storage/media/downloads:/downloads"
#      - "/mnt/storage/media/comics:/comics"
#  gaps:
#    container_name: gaps
#    expose: 
#      - "32400"
#    environment:
#      - TZ=America/Chicago
#      - "PUID=${PUID}"
#      - "PGID=${PGID}"
#    image: housewrecker/gaps:latest-no-ssl
#    restart: unless-stopped
#    labels:
#      - traefik.enable=true
#      - traefik.backend=gaps
#      - "traefik.frontend.rule=Host:gaps.${DOMAINNAME}"
#      - traefik.port=8484
#      - traefik.docker.network=traefik_proxy
#      - traefik.frontend.headers.SSLRedirect=true
#      - traefik.frontend.headers.STSSeconds=315360000
#      - traefik.frontend.headers.browserXSSFilter=true
#      - traefik.frontend.headers.contentTypeNosniff=true
#      - traefik.frontend.headers.forceSTSHeader=true
#      - traefik.frontend.headers.SSLHost=frost.haus
#      - traefik.frontend.headers.STSIncludeSubdomains=true
#      - traefik.frontend.headers.STSPreload=true
#      - traefik.frontend.headers.frameDeny=false
#    networks:
#      - traefik_proxy
#    volumes:
#      - "/etc/localtime:/etc/localtime:ro"
  netdata: 
    environment: 
      - TZ=America/Chicago
      - "PUID=${PUID}"
      - "PGID=${PGID}"
    container_name: netdata
    image: netdata/netdata:latest
    labels: 
      # - traefik.frontend.auth.forward.address=http://oauth:4181
      # - traefik.frontend.auth.forward.authResponseHeaders=X-Forwarded-User
      # - traefik.frontend.auth.forward.trustForwardHeader=true
      - traefik.enable=true
      - traefik.backend=netdata
      - "traefik.frontend.rule=Host:netdata.${DOMAINNAME}"
      - traefik.port=19999
      - traefik.docker.network=traefik_proxy
      - traefik.frontend.headers.SSLRedirect=true
      - traefik.frontend.headers.STSSeconds=315360000
      - traefik.frontend.headers.browserXSSFilter=true
      - traefik.frontend.headers.contentTypeNosniff=true
      - traefik.frontend.headers.forceSTSHeader=true
      - traefik.frontend.headers.SSLHost=frost.haus
      - traefik.frontend.headers.STSIncludeSubdomains=true
      - traefik.frontend.headers.STSPreload=true
      - traefik.frontend.headers.frameDeny=false
    networks: 
      - traefik_proxy
    security_opt: 
      - "apparmor:unconfined"
    volumes: 
      - "/proc:/host/proc:ro"
      - "/sys:/host/sys:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/mnt/storage/appdata/netdata:/etc/netdata"
  organizr: 
    container_name: organizr
    environment: 
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "TZ=${TZ}"
    # image: lsiocommunity/organizr:latest
    image: linuxserver/organizr:amd64-latest
    labels: 
      - traefik.enable=true
      - traefik.backend=organizr
      - "traefik.frontend.rule=Host:${DOMAINNAME}"
      - traefik.port=80
      - traefik.docker.network=traefik_proxy
      - traefik.frontend.headers.SSLRedirect=true
      - traefik.frontend.headers.STSSeconds=315360000
      - traefik.frontend.headers.browserXSSFilter=true
      - traefik.frontend.headers.contentTypeNosniff=true
      - traefik.frontend.headers.forceSTSHeader=true
      - traefik.frontend.headers.SSLHost=frost.haus
      - traefik.frontend.headers.STSIncludeSubdomains=true
      - traefik.frontend.headers.STSPreload=true
      - traefik.frontend.headers.frameDeny=false
    networks: 
      - traefik_proxy
    restart: always
    volumes: 
      - "/mnt/storage/appdata/organizr:/config"
      - "/mnt/storage/appdata/shared:/shared"
  ouroboros: 
    container_name: ouroboros
    environment: 
      - CLEANUP=true
      - INTERVAL=300
      - LOG_LEVEL=info
      - SELF_UPDATE=true
      - "IGNORE=mongo influxdb postgres mariadb"
      - TZ=America/Chicago
    image: pyouroboros/ouroboros:latest
    restart: unless-stopped
    volumes: 
      - "/var/run/docker.sock:/var/run/docker.sock"
  plex:
    image: plexinc/pms-docker
    container_name: plex
    volumes:
      - /mnt/storage/media/download-reprocess:/download-reprocess
      - /mnt/storage/appdata/plex:/config
      - /mnt/storage-usb/media/tv:/data/tvshows
      - /mnt/storage/media/homemovies:/data/homemovies
      - /mnt/storage/media/photos:/data/photos
      - /mnt/storage/media/exercisevideos:/data/exercisevideos
      - /mnt/storage/media/movies:/data/movies
      - /mnt/storage/media/TEMP_POSTPROCESSING:/transcode
    environment:
      - VERSION=public
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Chicago
      - PLEX_CLAIM=${PLEX_CLAIM_CODE}
    network_mode: host
    restart: always
    volumes: 
      - "/mnt/storage/appdata/plex:/config"
      - "/mnt/storage/media/TEMP_POSTPROCESSING:/transcode"
      - "/mnt/storage-usb/media/tv:/data/tvshows"
      - "/mnt/storage/media/homemovies:/data/homemovies"
      - "/mnt/storage/media/photos:/data/photos"
      - "/mnt/storage/media/exercisevideos:/data/exercisevideos"
      - "/mnt/storage/media/movies:/data/movies"
      - "/mnt/storage/appdata/shared:/shared"
  portainer: 
    container_name: portainer
    image: portainer/portainer:latest
    labels: 
      - traefik.enable=true
      - traefik.backend=portainer
      - "traefik.frontend.rule=Host:portainer.${DOMAINNAME}"
      - traefik.port=9000
      - traefik.docker.network=traefik_proxy
      - traefik.frontend.headers.SSLRedirect=true
      - traefik.frontend.headers.STSSeconds=315360000
      - traefik.frontend.headers.browserXSSFilter=true
      - traefik.frontend.headers.contentTypeNosniff=true
      - traefik.frontend.headers.forceSTSHeader=true
      - traefik.frontend.headers.SSLHost=frost.haus
      - traefik.frontend.headers.STSIncludeSubdomains=true
      - traefik.frontend.headers.STSPreload=true
      - traefik.frontend.headers.frameDeny=false
    networks: 
      - traefik_proxy
    restart: always
    volumes: 
      - "/mnt/storage/appdata/portainer:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
  radarr: 
    container_name: radarr
    environment: 
      - "PUID=${PUID}"
      - "PGID=${PGID}"
    image: linuxserver/radarr:latest
    #image: linuxserver/radarr:preview
    labels: 
      - traefik.enable=true
      - traefik.backend=radarr
      - "traefik.frontend.rule=Host:radarr.${DOMAINNAME}"
      - traefik.port=7878
      - traefik.docker.network=traefik_proxy
      - traefik.frontend.headers.SSLRedirect=true
      - traefik.frontend.headers.STSSeconds=315360000
      - traefik.frontend.headers.browserXSSFilter=true
      - traefik.frontend.headers.contentTypeNosniff=true
      - traefik.frontend.headers.forceSTSHeader=true
      - traefik.frontend.headers.SSLHost=frost.haus
      - traefik.frontend.headers.STSIncludeSubdomains=true
      - traefik.frontend.headers.STSPreload=true
      - traefik.frontend.headers.frameDeny=false
    networks: 
      - traefik_proxy
    restart: always
    volumes: 
      - "/mnt/storage/appdata/radarr:/config"
      - "/mnt/storage/media/movies:/movies"
      - "/mnt/storage/media/downloads:/downloads"
      - "/mnt/storage/appdata/shared:/shared"
  sabnzbd: 
    container_name: sabnzbd
    environment: 
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - TZ=America/Chicago
    image: linuxserver/sabnzbd:latest
    labels: 
      - traefik.enable=true
      - traefik.backend=sabnzbd
      - "traefik.frontend.rule=Host:sabnzbd.${DOMAINNAME}"
      - traefik.port=8080
      - traefik.docker.network=traefik_proxy
      - traefik.frontend.headers.SSLRedirect=true
      - traefik.frontend.headers.STSSeconds=315360000
      - traefik.frontend.headers.browserXSSFilter=true
      - traefik.frontend.headers.contentTypeNosniff=true
      - traefik.frontend.headers.forceSTSHeader=true
      - traefik.frontend.headers.SSLHost=frost.haus
      - traefik.frontend.headers.STSIncludeSubdomains=true
      - traefik.frontend.headers.STSPreload=true
      - traefik.frontend.headers.frameDeny=false
    networks: 
      - traefik_proxy
    restart: always
    volumes: 
      - "/mnt/storage/appdata/sabnzbd/config:/config"
      - "/mnt/storage/media/incomplete-downloads:/incomplete-downloads"
      - "/mnt/storage/media/downloads:/downloads"
      - "/mnt/storage/appdata/shared:/shared"
  sonarr: 
    container_name: sonarr
    environment: 
      - "PUID=${PUID}"
      - "PGID=${PGID}"
    image: linuxserver/sonarr
    labels: 
      - traefik.enable=true
      - traefik.backend=sonarr
      - "traefik.frontend.rule=Host:sonarr.${DOMAINNAME}"
      - traefik.port=8989
      - traefik.docker.network=traefik_proxy
      - traefik.frontend.headers.SSLRedirect=true
      - traefik.frontend.headers.STSSeconds=315360000
      - traefik.frontend.headers.browserXSSFilter=true
      - traefik.frontend.headers.contentTypeNosniff=true
      - traefik.frontend.headers.forceSTSHeader=true
      - traefik.frontend.headers.SSLHost=frost.haus
      - traefik.frontend.headers.STSIncludeSubdomains=true
      - traefik.frontend.headers.STSPreload=true
      - traefik.frontend.headers.frameDeny=false
    links: 
      - sabnzbd
    networks: 
      - traefik_proxy
    restart: always
    volumes: 
      - "/mnt/storage/appdata/sonarr:/config"
      - "/mnt/storage/media/tv_import:/tv_import"
      - "/mnt/storage-usb/media/tv:/tv"
      - "/mnt/storage/media/downloads:/downloads"
      - "/mnt/storage/appdata/shared:/shared"
  tautulli: 
    container_name: tautulli
    depends_on: 
      - plex
    environment: 
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - TZ=America/Chicago
    image: linuxserver/tautulli:latest
    labels: 
      - traefik.enable=true
      - traefik.backend=tautulli
      - "traefik.frontend.rule=Host:tautulli.${DOMAINNAME}"
      - traefik.port=8181
      - traefik.docker.network=traefik_proxy
      - traefik.frontend.headers.SSLRedirect=true
      - traefik.frontend.headers.STSSeconds=315360000
      - traefik.frontend.headers.browserXSSFilter=true
      - traefik.frontend.headers.contentTypeNosniff=true
      - traefik.frontend.headers.forceSTSHeader=true
      - traefik.frontend.headers.SSLHost=frost.haus
      - traefik.frontend.headers.STSIncludeSubdomains=true
      - traefik.frontend.headers.STSPreload=true
      - traefik.frontend.headers.frameDeny=false
    links: 
      - plex
    networks: 
      - traefik_proxy
    restart: always
    volumes: 
      - "/mnt/storage/appdata/plexpy:/config"
      - "/mnt/storage/appdata/plex/Library/Application\\ Support/Plex\\ Media\\ Server/Logs:/logs:ro"
      - "/mnt/storage/appdata/shared:/shared"
  traefik: 
    container_name: traefik
    domainname: "${DOMAINNAME}"
    environment: 
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - TZ=America/Chicago
      - "CF_API_EMAIL=${CLOUDFLARE_EMAIL}"
      - "CF_API_KEY=${CLOUDFLARE_API_KEY}"
    hostname: traefik
    image: "traefik:1.7"
    dns: 8.8.8.8
    labels: 
      - traefik.enable=true
      - traefik.backend=traefik
      - "traefik.frontend.rule=Host:traefik.${DOMAINNAME}"
      - traefik.port=8080
      - traefik.docker.network=traefik_proxy
      - traefik.frontend.headers.SSLRedirect=true
      - traefik.frontend.headers.STSSeconds=315360000
      - traefik.frontend.headers.browserXSSFilter=true
      - traefik.frontend.headers.contentTypeNosniff=true
      - traefik.frontend.headers.forceSTSHeader=true
      - traefik.frontend.headers.SSLHost=frost.haus
      - traefik.frontend.headers.STSIncludeSubdomains=true
      - traefik.frontend.headers.STSPreload=true
      # - traefik.frontend.headers.frameDeny=false
      # - "traefik.frontend.auth.basic.users=${HTTP_USERNAME}:${HTTP_PASSWORD}"
      # Below is new section - test 2
      # - traefik.frontend.auth.forward.address=http://oauth:4181
      # - traefik.frontend.auth.forward.authResponseHeaders=X-Forwarded-User
      # - traefik.frontend.auth.forward.trustForwardHeader=true
      # New starts here
      - traefik.protocol=http
      - "traefik.frontend.headers.SSLHost=traefik.${DOMAINNAME}"
      - traefik.frontend.passHostHeader=true
      - traefik.frontend.headers.SSLForceHost=true
      - traefik.frontend.headers.customResponseHeaders=X-Robots-Tag:noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex
      - traefik.frontend.headers.frameDeny=true
      - "traefik.frontend.headers.customFrameOptionsValue=allow-from https:${DOMAINNAME}"
    networks: 
    - default
    - traefik_proxy
    ports: 
      - "80:80"
      - "443:443"
      - "8145:8080"
    restart: always
    volumes: 
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/mnt/storage/appdata/traefik:/etc/traefik"
      - "/mnt/storage/appdata/shared/traefik:/shared"
#  gazee:
#    image: linuxserver/gazee:latest
#    container_name: gazee
#    environment:
#      - "PUID=${PUID}"
#      - "PGID=${PGID}"
#    volumes:
#      - "/mnt/storage/appdata/gazee:/config"
#      - "/mnt/storage/media/comics:/comics"
#      - "/mnt/storage/appdata/mylar/mylar:/mylar"
#      - "/mnt/storage/appdata/gazee/certs:/certs"
#    restart: unless-stopped
#    labels: 
#      - traefik.enable=true
#      - traefik.backend=gazee
#      - "traefik.frontend.rule=Host:gazee.${DOMAINNAME}"
#      - traefik.port=4242
#      - traefik.docker.network=traefik_proxy
#      - traefik.frontend.headers.SSLRedirect=true
#      - traefik.frontend.headers.STSSeconds=315360000
#      - traefik.frontend.headers.browserXSSFilter=true
#      - traefik.frontend.headers.contentTypeNosniff=true
#      - traefik.frontend.headers.forceSTSHeader=true
#      - traefik.frontend.headers.SSLHost=frost.haus
#      - traefik.frontend.headers.STSIncludeSubdomains=true
#      - traefik.frontend.headers.STSPreload=true
#      - traefik.frontend.headers.frameDeny=false
  duplicati:
    image: linuxserver/duplicati:amd64-latest
    container_name: duplicati
    environment:
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - TZ=America/Chicago
    volumes:
      - "/mnt/storage/appdata/duplicati:/config"
      - /mnt:/source
    restart: unless-stopped
    labels: 
      - traefik.enable=true
      - traefik.backend=duplicati
      - "traefik.frontend.rule=Host:duplicati.${DOMAINNAME}"
      - traefik.port=8200
      - traefik.docker.network=traefik_proxy
      - traefik.frontend.headers.SSLRedirect=true
      - traefik.frontend.headers.STSSeconds=315360000
      - traefik.frontend.headers.browserXSSFilter=true
      - traefik.frontend.headers.contentTypeNosniff=true
      - traefik.frontend.headers.forceSTSHeader=true
      - traefik.frontend.headers.SSLHost=frost.haus
      - traefik.frontend.headers.STSIncludeSubdomains=true
      - traefik.frontend.headers.STSPreload=true
      - traefik.frontend.headers.frameDeny=false
  # oauth:
  #   image: thomseddon/traefik-forward-auth
  #   container_name: oauth
  #   hostname: oauth
  #   restart: always
  #   networks:
  #     - default
  #     - traefik_proxy
  #   environment:
  #     - "PROVIDERS_GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}"
  #     - "PROVIDERS_GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}"
  #     - "SECRET=${OAUTH_SECRET}"
  #     - "COOKIE_DOMAIN=${DOMAINNAME}"
  #     - INSECURE_COOKIE=false
  #     - "AUTH_HOST=oauth.${DOMAINNAME}"
  #     - URL_PATH=/_oauth
  #     - "WHITELIST=${MY_EMAIL}"
  #     - LOG_LEVEL=info
  #     - LIFETIME=2592000 # 30 days
  #   labels:
  #     - traefik.enable=true
  #     - traefik.backend=oauth
  #     - traefik.port=4181
  #     - "traefik.frontend.rule=Host:oauth.${DOMAINNAME}"
  #     - "traefik.frontend.headers.SSLHost=oauth.${DOMAINNAME}"
  #     - traefik.docker.network=traefik_proxy
  #     - traefik.frontend.passHostHeader=true
  #     - traefik.frontend.headers.SSLForceHost=true
  #     - traefik.frontend.headers.customResponseHeaders=X-Robots-Tag:noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex
  #     - traefik.frontend.headers.SSLRedirect=true
  #     - traefik.frontend.headers.browserXSSFilter=true
  #     - traefik.frontend.headers.contentTypeNosniff=true
  #     - traefik.frontend.headers.forceSTSHeader=true
  #     - traefik.frontend.headers.STSSeconds=315360000
  #     - traefik.frontend.headers.STSIncludeSubdomains=true
  #     - traefik.frontend.headers.STSPreload=true
  #     - traefik.frontend.headers.frameDeny=true
  #     - traefik.frontend.auth.forward.address=http://oauth:4181
  #     - traefik.frontend.auth.forward.authResponseHeaders=X-Forwarded-User
  #     - traefik.frontend.auth.forward.trustForwardHeader=true
