apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
    traefik.backend: gazee
    traefik.docker.network: traefik_proxy
    traefik.enable: "true"
    traefik.frontend.headers.SSLHost: frost.haus
    traefik.frontend.headers.SSLRedirect: "true"
    traefik.frontend.headers.STSIncludeSubdomains: "true"
    traefik.frontend.headers.STSPreload: "true"
    traefik.frontend.headers.STSSeconds: "315360000"
    traefik.frontend.headers.browserXSSFilter: "true"
    traefik.frontend.headers.contentTypeNosniff: "true"
    traefik.frontend.headers.forceSTSHeader: "true"
    traefik.frontend.headers.frameDeny: "false"
    traefik.frontend.rule: Host:gazee.FROST.HAUS
    traefik.port: "4242"
  creationTimestamp: null
  labels:
    io.kompose.service: gazee
  name: gazee
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: gazee
    spec:
      containers:
      - env:
        - name: PGID
          value: "1000"
        - name: PUID
          value: "1000"
        image: linuxserver/gazee:latest
        name: gazee
        resources: {}
        volumeMounts:
        - mountPath: /config
          name: gazee-claim0
        - mountPath: /comics
          name: gazee-claim1
        - mountPath: /mylar
          name: gazee-claim2
        - mountPath: /certs
          name: gazee-claim3
      restartPolicy: Always
      volumes:
      - name: gazee-claim0
        persistentVolumeClaim:
          claimName: gazee-claim0
      - name: gazee-claim1
        persistentVolumeClaim:
          claimName: gazee-claim1
      - name: gazee-claim2
        persistentVolumeClaim:
          claimName: gazee-claim2
      - name: gazee-claim3
        persistentVolumeClaim:
          claimName: gazee-claim3
status: {}
