apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
    traefik.backend: lazylibrarian
    traefik.docker.network: traefik_proxy
    traefik.enable: "true"
    traefik.frontend.headers.SSLHost: frost.haus
    traefik.frontend.headers.SSLRedirect: "true"
    traefik.frontend.headers.STSIncludeSubdomains: "true"
    traefik.frontend.headers.STSPreload: "true"
    traefik.frontend.headers.STSSeconds: "315360000"
    traefik.frontend.headers.browserXSSFilter: "true"
    traefik.frontend.headers.contentTypeNosniff: "true"
    traefik.frontend.headers.forceSTSHeader: "true"
    traefik.frontend.headers.frameDeny: "false"
    traefik.frontend.rule: Host:lazylibrarian.FROST.HAUS
    traefik.port: "5299"
  creationTimestamp: null
  labels:
    io.kompose.service: lazylibrarian
  name: lazylibrarian
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: lazylibrarian
    spec:
      containers:
      - env:
        - name: PGID
          value: "1000"
        - name: PUID
          value: "1000"
        - name: TZ
          value: America/Chicago
        image: linuxserver/lazylibrarian:latest
        name: lazylibrarian
        resources: {}
        volumeMounts:
        - mountPath: /config
          name: lazylibrarian-claim0
        - mountPath: /downloads
          name: lazylibrarian-claim1
        - mountPath: /books
          name: lazylibrarian-claim2
      restartPolicy: Always
      volumes:
      - name: lazylibrarian-claim0
        persistentVolumeClaim:
          claimName: lazylibrarian-claim0
      - name: lazylibrarian-claim1
        persistentVolumeClaim:
          claimName: lazylibrarian-claim1
      - name: lazylibrarian-claim2
        persistentVolumeClaim:
          claimName: lazylibrarian-claim2
status: {}
