apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
    traefik.backend: organizr
    traefik.docker.network: traefik_proxy
    traefik.enable: "true"
    traefik.frontend.headers.SSLHost: frost.haus
    traefik.frontend.headers.SSLRedirect: "true"
    traefik.frontend.headers.STSIncludeSubdomains: "true"
    traefik.frontend.headers.STSPreload: "true"
    traefik.frontend.headers.STSSeconds: "315360000"
    traefik.frontend.headers.browserXSSFilter: "true"
    traefik.frontend.headers.contentTypeNosniff: "true"
    traefik.frontend.headers.forceSTSHeader: "true"
    traefik.frontend.headers.frameDeny: "false"
    traefik.frontend.rule: Host:FROST.HAUS
    traefik.port: "80"
  creationTimestamp: null
  labels:
    io.kompose.service: organizr
  name: organizr
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: organizr
    spec:
      containers:
      - env:
        - name: PGID
          value: "1000"
        - name: PUID
          value: "1000"
        - name: TZ
          value: America/Chicago
        image: lsiocommunity/organizr:latest
        name: organizr
        resources: {}
        volumeMounts:
        - mountPath: /config
          name: organizr-claim0
        - mountPath: /shared
          name: organizr-claim1
      restartPolicy: Always
      volumes:
      - name: organizr-claim0
        persistentVolumeClaim:
          claimName: organizr-claim0
      - name: organizr-claim1
        persistentVolumeClaim:
          claimName: organizr-claim1
status: {}
