apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: ouroboros
  name: ouroboros
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: ouroboros
    spec:
      containers:
      - env:
        - name: CLEANUP
          value: "true"
        - name: IGNORE
          value: mongo influxdb postgres mariadb
        - name: INTERVAL
          value: "300"
        - name: LOG_LEVEL
          value: info
        - name: SELF_UPDATE
          value: "true"
        - name: TZ
          value: America/Chicago
        image: pyouroboros/ouroboros:latest
        name: ouroboros
        resources: {}
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: ouroboros-claim0
      restartPolicy: Always
      volumes:
      - name: ouroboros-claim0
        persistentVolumeClaim:
          claimName: ouroboros-claim0
status: {}
