apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
    traefik.backend: radarr
    traefik.docker.network: traefik_proxy
    traefik.enable: "true"
    traefik.frontend.headers.SSLHost: frost.haus
    traefik.frontend.headers.SSLRedirect: "true"
    traefik.frontend.headers.STSIncludeSubdomains: "true"
    traefik.frontend.headers.STSPreload: "true"
    traefik.frontend.headers.STSSeconds: "315360000"
    traefik.frontend.headers.browserXSSFilter: "true"
    traefik.frontend.headers.contentTypeNosniff: "true"
    traefik.frontend.headers.forceSTSHeader: "true"
    traefik.frontend.headers.frameDeny: "false"
    traefik.frontend.rule: Host:radarr.FROST.HAUS
    traefik.port: "7878"
  creationTimestamp: null
  labels:
    io.kompose.service: radarr
  name: radarr
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: radarr
    spec:
      containers:
      - env:
        - name: PGID
          value: "1000"
        - name: PUID
          value: "1000"
        image: linuxserver/radarr:latest
        name: radarr
        resources: {}
        volumeMounts:
        - mountPath: /config
          name: radarr-claim0
        - mountPath: /movies
          name: radarr-claim1
        - mountPath: /downloads
          name: radarr-claim2
        - mountPath: /shared
          name: radarr-claim3
      restartPolicy: Always
      volumes:
      - name: radarr-claim0
        persistentVolumeClaim:
          claimName: radarr-claim0
      - name: radarr-claim1
        persistentVolumeClaim:
          claimName: radarr-claim1
      - name: radarr-claim2
        persistentVolumeClaim:
          claimName: radarr-claim2
      - name: radarr-claim3
        persistentVolumeClaim:
          claimName: radarr-claim3
status: {}
