apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
    traefik.backend: sabnzbd
    traefik.docker.network: traefik_proxy
    traefik.enable: "true"
    traefik.frontend.headers.SSLHost: frost.haus
    traefik.frontend.headers.SSLRedirect: "true"
    traefik.frontend.headers.STSIncludeSubdomains: "true"
    traefik.frontend.headers.STSPreload: "true"
    traefik.frontend.headers.STSSeconds: "315360000"
    traefik.frontend.headers.browserXSSFilter: "true"
    traefik.frontend.headers.contentTypeNosniff: "true"
    traefik.frontend.headers.forceSTSHeader: "true"
    traefik.frontend.headers.frameDeny: "false"
    traefik.frontend.rule: Host:sabnzbd.FROST.HAUS
    traefik.port: "8080"
  creationTimestamp: null
  labels:
    io.kompose.service: sabnzbd
  name: sabnzbd
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: sabnzbd
    spec:
      containers:
      - env:
        - name: PGID
          value: "1000"
        - name: PUID
          value: "1000"
        - name: TZ
          value: America/Chicago
        image: linuxserver/sabnzbd:latest
        name: sabnzbd
        resources: {}
        volumeMounts:
        - mountPath: /config
          name: sabnzbd-claim0
        - mountPath: /incomplete-downloads
          name: sabnzbd-claim1
        - mountPath: /downloads
          name: sabnzbd-claim2
        - mountPath: /shared
          name: sabnzbd-claim3
      restartPolicy: Always
      volumes:
      - name: sabnzbd-claim0
        persistentVolumeClaim:
          claimName: sabnzbd-claim0
      - name: sabnzbd-claim1
        persistentVolumeClaim:
          claimName: sabnzbd-claim1
      - name: sabnzbd-claim2
        persistentVolumeClaim:
          claimName: sabnzbd-claim2
      - name: sabnzbd-claim3
        persistentVolumeClaim:
          claimName: sabnzbd-claim3
status: {}
