apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
    traefik.backend: traefik
    traefik.docker.network: traefik_proxy
    traefik.enable: "true"
    traefik.frontend.auth.basic.users: bfrost:$apr1$IDMtbeie$3xqwgNt.nwU6tGTHhan5W0
    traefik.frontend.headers.SSLHost: frost.haus
    traefik.frontend.headers.SSLRedirect: "true"
    traefik.frontend.headers.STSIncludeSubdomains: "true"
    traefik.frontend.headers.STSPreload: "true"
    traefik.frontend.headers.STSSeconds: "315360000"
    traefik.frontend.headers.browserXSSFilter: "true"
    traefik.frontend.headers.contentTypeNosniff: "true"
    traefik.frontend.headers.forceSTSHeader: "true"
    traefik.frontend.headers.frameDeny: "false"
    traefik.frontend.rule: Host:traefik.FROST.HAUS
    traefik.port: "8080"
  creationTimestamp: null
  labels:
    io.kompose.service: traefik
  name: traefik
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: traefik
    spec:
      containers:
      - env:
        - name: CF_API_EMAIL
          value: bfrost@brainboy.com
        - name: CF_API_KEY
          value: e3aee298e536ceb2c3aeef2ba4485681fbe3f
        - name: PGID
          value: "1000"
        - name: PUID
          value: "1000"
        - name: TZ
          value: America/Chicago
        image: traefik:1.7
        name: traefik
        ports:
        - containerPort: 80
        - containerPort: 443
        resources: {}
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: traefik-claim0
          readOnly: true
        - mountPath: /etc/traefik
          name: traefik-claim1
        - mountPath: /shared
          name: traefik-claim2
      hostname: traefik
      restartPolicy: Always
      subdomain: FROST.HAUS
      volumes:
      - name: traefik-claim0
        persistentVolumeClaim:
          claimName: traefik-claim0
          readOnly: true
      - name: traefik-claim1
        persistentVolumeClaim:
          claimName: traefik-claim1
      - name: traefik-claim2
        persistentVolumeClaim:
          claimName: traefik-claim2
status: {}
